version: '3'


services:
  web:
    container_name: ${APP_NAME}_web
    build:
      context: ./docker/web
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/app
    
  db:
    container_name: ${APP_NAME}_db
    image: postgres:10.6
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=homestead
      - POSTGRES_DB=homestead